;; This code was automatically generated by the 'metav' library.
(ns version)

(def module-name "rpl")
(def path ".")
(def version "0.0.2")
(def tag "v0.0.2")
(def generated-at "2023-11-01T20:06:18Z")
